### ISSUE TITLE
[DOCS]: Improve django-cookiecutter tutorials

### ISSUE THREAD

**Issue by imAsparky** [imAsparky/django-cookiecutter#188]
**Describe alternatives you've considered**
Would you please share your clear and concise description of any alternative/similar documentation you've considered.

**Additional context**
Would you please share any other context or screenshots about the documentation request here.

**Comment by imAsparky** [comment]
Fix order of cookiecutter options in create cookiecutter.  These have been modified.

**Comment by rsevs3** [comment]
The command to activate the virtual environment is incorrect. The virtual environment name is my_venve.

![image](https://user-images.githubusercontent.com/2338952/146461465-4b4b16d9-768c-4c73-9e1a-f2dd6246d9a5.png)

**Comment by rsevs3** [comment]
The following file structure is incorrect. The cookiecutter now has different stages of development. The documentation needs to be clarified around this and clear about how to bring up a local django server.

![image](https://user-images.githubusercontent.com/2338952/146462755-c8d0f3b7-af53-41f5-aa87-be6fb2deae9e.png)

**Comment by rsevs3** [comment]
The output from the secret key should not be in the code example, when using the copy button, this copies the docs key as well.

![image](https://user-images.githubusercontent.com/2338952/146462913-aa6f655e-6879-4a36-930e-f660e2223628.png)

**Comment by rsevs3** [comment]
Django is not installed when trying to create the secret key. Add step:

pip install -r requirements-dev.txt

**Comment by rsevs3** [comment]
There is nothing in the tutorial to change to the my-new-django directory. This either needs to be added, or the following command changed to account for the file structure:

python3 manage.py makemigrations

**Comment by rsevs3** [comment]
If ALLOWED_HOSTS and INTERNAL_IPS is left blank during the cookicutter steps, it is not created and causes errors when running makemigrations

**Comment by rsevs3** [comment]
There is nothing in the setup about EMAIL_BACKEND. With this environment variable not created, it is causing an error in makemigrations.

**Comment by rsevs3** [comment]
This does not make it clear that another command is being run in the second code block. Also, keep commands and outputs separate so you can use the copy code button.

![image](https://user-images.githubusercontent.com/2338952/146465017-2b21b95e-ef88-4e33-81ea-3ff76b1efc25.png)

**Comment by rsevs3** [comment]
When the django server is up and running, there is no CSS to style the page.

![image](https://user-images.githubusercontent.com/2338952/146616085-f55112ba-6966-4c86-951b-c2606822bf5f.png)

**Comment by imAsparky** [comment]
Update pre-requisites to py3.8 or greater for Django 4.0

**Comment by rsevs3** [comment]
There needs to be a step to add the static files in the tutorial.

python3 manage.py collectstatic

**Comment by rsevs3** [comment]
In order to get the allauth templates to update from the /templates/account folder, the templates folder needs to be added in to the base.py templates DIRS as follows:

![image](https://user-images.githubusercontent.com/2338952/147311759-f006ead4-6106-4847-99e0-24aba6731c2e.png)

**Comment by imAsparky** [comment]
[COMPLETE]

Example Django Project does not match cookiecutter order of selection.

![image](https://user-images.githubusercontent.com/31756570/147525952-b84df5b7-3830-425b-a923-a76caf7f49ba.png)

**Comment by rsevs3** [comment]
Consideration: Add a note in the documentation before the migrations are executed that if a custom user model is going to be implemented, this needs to be added before database migrations.

**Comment by rsevs3** [comment]
Consideration: Move base.html out of /templates/account to /templates

This will require each template in /accounts to have the extends updated as follows {% extends "base.html" %}
